version: "3.7"

services:
  webserver:
    container_name: webserver
    image: nginx
    ports:
      - "80:80"
    volumes:
    - ./config/nginx/sites:/etc/nginx/conf.d
  backend:
    container_name: php
    build:
      context: ./config/php
    expose:
      - "9000"