version: "3.7"

services:
  webserver:
    container_name: webserver
    image: nginx
    ports:
      - "80:80"
    volumes:
    - ./config/nginx/sites:/etc/nginx/conf.d
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./config/php
    expose:
      - "9000"
    volumes:
    - ./back:/home/backend
